### ISSUE TITLE
Crashes on 32 bit platforms

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/ipproxy#13]
I see this on android

```
06-10 01:18:48.225 21158     0 E Go      : panic: unaligned 64-bit atomic operation
06-10 01:18:48.225 21158     0 E Go      :
06-10 01:18:48.225 21158     0 E Go      : goroutine 627 [running]:
06-10 01:18:48.226 21158     0 E Go      : runtime/internal/atomic.panicUnaligned()
06-10 01:18:48.226 21158     0 E Go      : 	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2c
06-10 01:18:48.226 21158     0 E Go      : runtime/internal/atomic.Store64(0x86df382c, 0x8000, 0x0)
06-10 01:18:48.226 21158     0 E Go      : 	/usr/local/go/src/runtime/internal/atomic/asm_arm.s:278 +0x14
06-10 01:18:48.228 21158     0 E Go      : gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetReceiveBufferSize(0x86df37b4, 0x8000, 0x0, 0xffffff00)
06-10 01:18:48.229 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210505070627-d7b76c1526b6/pkg/tcpip/socketops.go:661 +0x1ac
06-10 01:18:48.229 21158     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/udp.newEndpoint(0x8973f180, 0x800, 0x88925800, 0x8973f180)
06-10 01:18:48.229 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210505070627-d7b76c1526b6/pkg/tcpip/transport/udp/endpoint.go:185 +0x1ac
06-10 01:18:48.229 21158     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/transport/udp.(*protocol).NewEndpoint(0x89d0b4d0, 0x800, 0x88925800, 0x88d0c6b8, 0x1, 0x0, 0x0)
06-10 01:18:48.229 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210505070627-d7b76c1526b6/pkg/tcpip/transport/udp/protocol.go:58 +0x30
06-10 01:18:48.230 21158     0 E Go      : gvisor.dev/gvisor/pkg/tcpip/stack.(*Stack).NewEndpoint(0x8973f180, 0x11, 0x800, 0x88925800, 0x4, 0x0, 0x0, 0x0)
06-10 01:18:48.230 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210505070627-d7b76c1526b6/pkg/tcpip/stack/stack.go:584 +0x6c
06-10 01:18:48.230 21158     0 E Go      : github.com/getlantern/ipproxy.(*origin).init(0x87a1e880, 0x11, 0x1, 0x0, 0x0, 0x896c0035, 0x7, 0x35)
06-10 01:18:48.230 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/github.com/getlantern/ipproxy@v0.0.0-20210513141610-564063eeb53e/base.go:282 +0x1f0
06-10 01:18:48.230 21158     0 E Go      : github.com/getlantern/ipproxy.(*proxy).startUDPConn(0x88d17180, 0x896cf3e0, 0x8, 0x44f3, 0x896cf3e8, 0x7, 0x35, 0x27, 0x5c8, 0x896cf3e0)
06-10 01:18:48.230 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/github.com/getlantern/ipproxy@v0.0.0-20210513141610-564063eeb53e/udp.go:59 +0x238
06-10 01:18:48.230 21158     0 E Go      : github.com/getlantern/ipproxy.(*proxy).onUDP(0x88d17180, 0x880c7800, 0x3b, 0x5dc, 0x1104, 0x8b77bf08, 0x8b77bf20, 0x880c7814, 0x27, 0x5c8)
06-10 01:18:48.230 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/github.com/getlantern/ipproxy@v0.0.0-20210513141610-564063eeb53e/udp.go:23 +0x250
06-10 01:18:48.230 21158     0 E Go      : github.com/getlantern/ipproxy.(*proxy).copyToUpstream(0x88d17180, 0x8826b880, 0x86d2c7c0, 0x896cf2a0)
06-10 01:18:48.231 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/github.com/getlantern/ipproxy@v0.0.0-20210513141610-564063eeb53e/ipproxy.go:238 +0x1dc
06-10 01:18:48.231 21158     0 E Go      : created by github.com/getlantern/ipproxy.(*proxy).Serve
06-10 01:18:48.231 21158     0 E Go      : 	/var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/gomobile-work-163720389/pkg/mod/github.com/getlantern/ipproxy@v0.0.0-20210513141610-564063eeb53e/ipproxy.go:159 +0xec
```

**Comment by oxtoacart** [comment]
I'm remembering now that one of the things we had to do in our fork of netstack was to fix some of their structs to make sure alignment works on 32 bit platforms. I also had to change initial slow start threshold to something that's representable in 32 bit ints (not sure if that's still an issue).

Here are some potentially relevant commits.

https://github.com/getlantern/netstack/commit/1650eee50330132cd367ab5d022c2e49d44c4ec5
https://github.com/getlantern/netstack/commit/f54213f594e96f64375765f7dfe5557f77735f22

**Comment by oxtoacart** [comment]
Here are some relevant gvisor tickets:

https://github.com/google/gvisor/issues/1446
https://github.com/google/gvisor/issues/5692

From that 2nd bug, it looks like they won't commit to officially supporting 32 bit platforms, so even if we manage to get a PR in to fix this upstream, it may break again on subsequent releases.

**Comment by reflog** [comment]
@oxtoacart sounds like we should just rollback the changes. If they are not supporting our required architecture...

**Comment by oxtoacart** [comment]
> @oxtoacart sounds like we should just rollback the changes. If they are not supporting our required architecture...

Yeah, or we could fork gvisor the way we forked netstack, and periodically take updates from upstream.

**Comment by kevinGC** [comment]
Hello from the gVisor team. That panic on 32 bit machines was fixed [here](https://github.com/google/gvisor/pull/6009). Maybe update `go.mod`?

We can't officially commit to supporting architectures outside of arm64 and amd64, so I understand if you choose to fork. But we're happy to merge PRs that add support and to look into bugs. If you choose to fork, upstreaming is always appreciated.

**Comment by reflog** [comment]
thanks @kevinGC we'll give it a try!

**Comment by reflog** [comment]
@oxtoacart I've created  a branch with up-to-date gvisor https://github.com/getlantern/ipproxy/pull/14 .
I'm not sure how to test it on Android though

**Comment by oxtoacart** [comment]
@reflog That fixed it, thanks!

Thanks @kevinGC !
